# Compiler
CC = nvcc

# Compiler flags
LDLIBS = -lm
CFLAGS = -Wno-deprecated-gpu-targets -gencode=arch=compute_70,code=sm_70 -O3 -Xcompiler --openmp,-Wall

SRC = src

# Source files (OpenMP v2 variant)
SRCS = $(SRC)/main.c $(SRC)/lenia_openmp_v2.cu $(SRC)/orbium.c $(SRC)/gifenc.c

# Header files
HDRS = $(wildcard $(SRC)/*.h)

# Object files
OBJS_1 = $(SRCS:$(SRC)/%.c=%.o)
OBJS = $(OBJS_1:$(SRC)/%.cu=%.o)

# Executable name
TARGET = lenia_openmp_v2.out

# Build target
$(TARGET): $(OBJS)
	$(CC) $(CFLAGS) $(OBJS) -o $(TARGET) $(LDLIBS)

# Compile source files to object files
%.o: $(SRC)/%.cu $(HDRS)
	$(CC) $(CFLAGS) -c -o $@ $<

%.o: $(SRC)/%.c $(HDRS)
	$(CC) $(CFLAGS) -c -o $@ $<

# Clean
clean:
	rm -f $(OBJS) $(TARGET)